const FLOWERS_CLASS_NAMES = [
  "pink primrose",
  "hard-leaved pocket orchid",
  "canterbury bells",
  "sweet pea",
  "wild rose",
  "tiger lily",
  "moon orchid",
  "bird of paradise",
  "monkshood",
  "globe thistle",
  "snapdragon",
  "colt's foot",
  "king protea",
  "spear thistle",
  "yellow iris",
  "globe-flower",
  "purple coneflower",
  "peruvian lily",
  "balloon flower",
  "giant white arum lily",
  "fire lily",
  "pincushion flower",
  "fritillary",
  "red ginger",
  "grape hyacinth",
  "corn poppy",
  "prince of wales feathers",
  "stemless gentian",
  "artichoke flower",
  "sweet william",
  "carnation",
  "garden phlox",
  "love in the mist",
  "mexican petunia",
  "bromelia",
  "blanket flower",
  "trumpet creeper",
  "blackberry lily",
  "beard flower",
  "silverbush",
  "californian poppy",
  "osteospermum",
  "rue",
  "clematis",
  "hibiscus",
  "columbine",
  "desert-rose",
  "tree mallow",
  "magnolia",
  "cyclamen",
  "water lily",
  "rose",
  "thorn apple",
  "morning glory",
  "passion flower",
  "lotus",
  "toad lily",
  "anthurium",
  "frangipani",
  "clethra",
  "marigold",
  "buttercup",
  "oxeye daisy",
  "common dandelion",
  "poinsettia",
  "bolero deep blue",
  "wallflower",
  "maroon marigold",
  "buttercup yellow",
  "wallflower purple",
  "primula",
  "carnation pink",
  "english daisy",
  "bee balm",
  "ball moss",
  "garland chrysanthemum",
  "barberton daisy",
  "petunia",
  "purple anemone",
  "bougainvillea",
  "camellia",
  "california poppy",
  "gloxinia",
  "geranium",
  "daisy",
  "raisin",
  "azalea",
  "mexican aster",
  "daffodil",
  "dandelion",
  "calla lily",
  "bromelia red",
  "mallow",
  "buttercup field",
  "passionfruit flower",
  "foxglove",
  "bellflower",
  "lilac hibiscus",
  "sunflower",
  "garden petunia",
  "tree dahlia",
  "wild pansy",
  "pincushion protea",
  "bishop’s flower",
  "gaura",
  "godetia",
  "alpine sea holly",
  "love lies bleeding"
];
